<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Masasamjant.Framework.Windows</AssemblyName>
    <RootNamespace>Masasamjant.Windows</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Masasamjant.Framework" Version="2.2.0" />
  </ItemGroup>

</Project>
