//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masasamjant.Security.Passwords.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasswordInvalidityReasonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordInvalidityReasonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Masasamjant.Security.Passwords.Resources.PasswordInvalidityReasonResource", typeof(PasswordInvalidityReasonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All characters in the password are same..
        /// </summary>
        internal static string AllCharactersAreSame {
            get {
                return ResourceManager.GetString("AllCharactersAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty or every character is whitespace character..
        /// </summary>
        internal static string EmptyOrWhitespaceOnly {
            get {
                return ResourceManager.GetString("EmptyOrWhitespaceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password ends with whitespace character..
        /// </summary>
        internal static string EndWithWhitespace {
            get {
                return ResourceManager.GetString("EndWithWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not contain any lowercase letters..
        /// </summary>
        internal static string NoLowerCaseLetters {
            get {
                return ResourceManager.GetString("NoLowerCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not contains enough number characters..
        /// </summary>
        internal static string NotEnoughNumbers {
            get {
                return ResourceManager.GetString("NotEnoughNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not contain enough special characters..
        /// </summary>
        internal static string NotEnoughSpecialCharacters {
            get {
                return ResourceManager.GetString("NotEnoughSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not contain any uppercase letters..
        /// </summary>
        internal static string NoUpperCaseLetters {
            get {
                return ResourceManager.GetString("NoUpperCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password starts with whitespace character..
        /// </summary>
        internal static string StartWithWhitespace {
            get {
                return ResourceManager.GetString("StartWithWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long..
        /// </summary>
        internal static string TooLong {
            get {
                return ResourceManager.GetString("TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short..
        /// </summary>
        internal static string TooShort {
            get {
                return ResourceManager.GetString("TooShort", resourceCulture);
            }
        }
    }
}
